//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommesseVecchia
    {
        public int IdCommessa { get; set; }
        public string Commessa { get; set; }
        public Nullable<int> IdSocieta { get; set; }
        public Nullable<int> IdBusinessUnit { get; set; }
    
        public virtual BusinessUnit BusinessUnit { get; set; }
        public virtual Societa Societa { get; set; }
    }
}
