//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManutenzioniVeicoli
    {
        public int IdManutenzioneVeicoli { get; set; }
        public System.DateTime Data { get; set; }
        public int IdVeicolo { get; set; }
        public int IdCausaleManutenzione { get; set; }
        public string Note { get; set; }
        public int IdFornitore { get; set; }
        public decimal Costo { get; set; }
        public Nullable<int> IdDocumento { get; set; }
    
        public virtual CausaliManutenzione CausaliManutenzione { get; set; }
        public virtual Documenti Documenti { get; set; }
        public virtual Fornitori Fornitori { get; set; }
        public virtual Veicoli Veicoli { get; set; }
    }
}
