//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car_App
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarDbEntities : DbContext
    {
        public CarDbEntities()
            : base("name=CarDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AnagraficaVecchia> AnagraficaVecchias { get; set; }
        public virtual DbSet<BusinessUnit> BusinessUnits { get; set; }
        public virtual DbSet<CausaliManutenzione> CausaliManutenziones { get; set; }
        public virtual DbSet<CommesseVecchia> CommesseVecchias { get; set; }
        public virtual DbSet<Documenti> Documentis { get; set; }
        public virtual DbSet<Email> Emails { get; set; }
        public virtual DbSet<Fornitori> Fornitoris { get; set; }
        public virtual DbSet<ManutenzioniVeicoli> ManutenzioniVeicolis { get; set; }
        public virtual DbSet<Modalita> Modalitas { get; set; }
        public virtual DbSet<Pedaggi> Pedaggis { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<Scadenze> Scadenzes { get; set; }
        public virtual DbSet<ScadenzeVeicoli> ScadenzeVeicolis { get; set; }
        public virtual DbSet<Societa> Societas { get; set; }
        public virtual DbSet<Stati> Statis { get; set; }
        public virtual DbSet<StatoVeicoli> StatoVeicolis { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TelepassViacard> TelepassViacards { get; set; }
        public virtual DbSet<UtilizzoVeicoli> UtilizzoVeicolis { get; set; }
        public virtual DbSet<Veicoli> Veicolis { get; set; }
    }
}
