//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documenti
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Documenti()
        {
            this.ManutenzioniVeicolis = new HashSet<ManutenzioniVeicoli>();
            this.ScadenzeVeicolis = new HashSet<ScadenzeVeicoli>();
            this.StatoVeicolis = new HashSet<StatoVeicoli>();
            this.StatoVeicolis1 = new HashSet<StatoVeicoli>();
        }
    
        public int IdDocumento { get; set; }
        public byte[] Documento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManutenzioniVeicoli> ManutenzioniVeicolis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScadenzeVeicoli> ScadenzeVeicolis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StatoVeicoli> StatoVeicolis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StatoVeicoli> StatoVeicolis1 { get; set; }
    }
}
