//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedaggi
    {
        public int IdPedaggi { get; set; }
        public string TelepassViacard { get; set; }
        public Nullable<int> Mese { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string Percorso { get; set; }
        public string Classe { get; set; }
        public Nullable<decimal> Costo { get; set; }
    }
}
