//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScadenzeVeicoli
    {
        public int IdScadenzeVeicoli { get; set; }
        public int IdVeicolo { get; set; }
        public System.DateTime Data { get; set; }
        public int IdScadenza { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public Nullable<int> IdDocumento { get; set; }
        public string Note { get; set; }
        public Nullable<bool> Avviso { get; set; }
        public Nullable<bool> AvvisoInviato { get; set; }
    
        public virtual Documenti Documenti { get; set; }
        public virtual Scadenze Scadenze { get; set; }
        public virtual Veicoli Veicoli { get; set; }
    }
}
