//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatoVeicoli
    {
        public int IdStatoVeicolo { get; set; }
        public int IdVeicolo { get; set; }
        public Nullable<int> IdProprieta { get; set; }
        public Nullable<int> IdLibretto { get; set; }
        public Nullable<int> IdTelepass { get; set; }
        public Nullable<int> IdViacard { get; set; }
        public System.DateTime Data { get; set; }
        public int IdStato { get; set; }
        public Nullable<int> ChilometriRental { get; set; }
        public int IdSocieta { get; set; }
        public Nullable<int> IdBusinessUnit { get; set; }
        public int IdModalita { get; set; }
        public string Note { get; set; }
        public Nullable<System.Guid> IdAnagrafica { get; set; }
    
        public virtual BusinessUnit BusinessUnit { get; set; }
        public virtual Documenti Documenti { get; set; }
        public virtual Documenti Documenti1 { get; set; }
        public virtual Modalita Modalita { get; set; }
        public virtual Societa Societa { get; set; }
        public virtual Stati Stati { get; set; }
        public virtual TelepassViacard TelepassViacard { get; set; }
        public virtual TelepassViacard TelepassViacard1 { get; set; }
        public virtual Veicoli Veicoli { get; set; }
    }
}
